# This is a configuration template
# To get started, copy this file, rename it "config.yaml" and fill in the bot's token
# Alternatively, if you have multiple bots, it is also possible to fill multiple copies of this file
# To make the program load a different config file from the default "config.yaml", pass its path as the first parameter
# For example, if you have "vk.yaml" and "tg.yaml" filled for different bots, then using them is done through these commands:
#   > echobot "vk.yaml"
#   > echobot "tg.yaml"
# Or, if you use Stack to lauch the program, then the corresponding commands become:
#   > stack run "vk.yaml"
#   > stack run "tg.yaml"


# The list of places that will receive the program log
# Possible values:
# - "null" # drops all messages
# - "std" # prints messages into the standard output
# - file: "filename" # appends messages to the specified file
# - filter: # filters messages passed to the destination
#     level: "debug"|"info"|"warn"|"err" # the level threshold of the messages
#     of: logger # the destination that receives the filtered messages,
#                # either a single logger from this list or an array of them
# The default is a singular "std"
logger:
  - file: EchoBot.log
  - filter:
      level: warn
      of: std


# Each submodule can be given individual verbosity level
# Possible verbosity levels, in decreasing order:
# "debug" > "info" > "warn" > "err" > "none"
# The default is to output everything ("debug")
web-log-level: debug
channel-log-level: debug
responder-log-level: debug


# Chosen front-end for the bot
channel:
  # The bot server and protocol, either "tg" for Telegram or "vk" for Vkontakte
  type: tg
  # type: vk
  # The Telegram bot token
  # This token includes the word "bot" in front of it
  # -------------------- This field must be set!  --------------------
  tg-token: bot1234567890:ABCDEFGHIJKL__mnopqrstuvwxyz0123456
  # The Vkontakte bot token
  vk-token: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234
  # The group id of the Vkontakte bot
  vk-group-id: 123456789
  # Timeout for the long polling, in seconds
  # The default is 60
  timeout: 60
  # Maximum number of buttons in a single row of a keyboard
  # When the back-end sends more buttons than this value, they are broken into multiple rows
  # The default is 5
  keyboard-width: 5


# Chosen back-end for the bot
# Only "repeat" is supported
responder:
  repeat:
    # The starting multiplier, used for chats where no explicit setting was made
    # The default is 3
    default-multiplier: 3
    # This message is sent when the bot is given an unknown command
    unknown-command-msg: |
      Неизвестная команда. Чтобы получить список доступных комманд, отправьте /help
    # The command to start chatting with the bot
    # This command simply sends the message below
    # The default is "/start"
    start-cmd: /start
    # This message is sent in response to the above command
    # In this message, %1 stands for the current multiplier in the current chat
    start-msg: &start-msg |
      Этот бот повторяет отправленные ему сообщения указанное число раз
      Текущий множитель: %1
      /repeat - установить новый множитель
    # The command to print the description of the bot
    # This command simply sends the message below
    # The default is "/help"
    describe-cmd: /help
    # This message is sent in response to the above command
    # In this message, %1 stands for the current multiplier in the current chat
    describe-msg: *start-msg
    # The command to inspect and change the current multiplier
    # This command sends the message below, together with a set of buttons from 1 to max-multiplier, which would set the new multiplier upon clicking
    # The default is "/repeat"
    inspect-multiplier-cmd: /repeat
    # This message is sent in response to the above command
    # In this message, %1 stands for the current multiplier in the current chat
    inspect-multiplier-msg: |
      Текущий множитель: %1
      Выберите новый множитель из списка ниже:
    # Once a new multiplier is set, the message above is replaced with this one, and the keyboard is removed
    multiplier-set-msg: |
      Текущий множитель установлен: %1
    # Error messages below are sent into the chat when certain media cannot be sent back
    # This message is used for media types that are unknown to the bot
    # In this message, %1 stands for the typename of the media
    # This message is sent once for every distinct unknown typename
    media-unknown-type-msg: |
      В предыдущем сообщении встречен неизвестный тип вложения "%1"
    # This message is used for media that are impossible to re-send correctly (e. g. the server doesn't give a download link, and doesn't allow it to be sent directly either)
    # This message has no parameters and is sent at most once per the user's message
    media-unsupported-msg: |
      В предыдущем сообщении встречены вложения, которые невозможно переслать в целостности
    # This message is used when media should be possible to re-send, but trying to actually do that has resulted in an error (e. g. the download link is there, but gives a 404)
    # The actual error is not shown to the user, but is still recorded to the log at "err" level
    # This message has no parameters and is sent at most once per the user's message
    media-internal-error-msg: |
      В ходе пересылки некоторых вложений возникли непредвиженные ошибки
    # This is the maximum multiplier that the bot allows to be set
    # The default is 5
    max-multiplier: 5
