name:                EchoBot
version:             0.1.0.0
github:              "githubuser/EchoBot"
license:             BSD3
author:              "Evgeny Osipenko"
maintainer:          "delfigamer@yandex.ru"
copyright:           "2020 Evgeny Osipenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/EchoBot#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 1
- text >= 1.2 && < 2
- req >= 3.2 && < 4
- aeson >= 1.4 && < 2

library:
  source-dirs: src

executables:
  EchoBot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EchoBot

tests:
  EchoBot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EchoBot
